### ISSUE TITLE
Shape is invalid for input of size when evaluating.

### ISSUE THREAD

**Issue by SHUzhekiNg** [rsamf/kdd-cup-23#1]
Hi, thanks for your open source code, and unfortunately i met a problem that confusing me.
I am using Python3.10 and I installed all the packages in the requirements.txt except two:
torch-scatter==2.1.1+pt20cu118
torch-sparse==0.6.17+pt20cu118
(but it seems that the two packages have never been used)

I first ran `sr_san_preprocessing.py` and got 3 counts.csv and 6 embeddings respectively and successfully.
And then i trained the network through `sr_san.py`, with no modification to the parameters and the code, except that i opened up the note from line19 to 21 since i am using the old data. The training process is done successfully as well.

But i met the problem when evaluating the model.
Here's my error message:

Traceback (most recent call last):
  File "/home/zhenglc2306/22Summer-KDD/sr_san.py", line 70, in <module>
    model.eval(loaders, sets, models, DEVICE)
  File "/home/zhenglc2306/22Summer-KDD/sr_san/model.py", line 187, in eval
    pred = model(x_id, x_title, x_desc, src_mask, src_key_padding_mask)
  File "/home/zhenglc2306/.conda/envs/kdd-cup-23/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/zhenglc2306/22Summer-KDD/sr_san/model.py", line 91, in forward
    pid = encode(pid, self.pid_encoder)
  File "/home/zhenglc2306/22Summer-KDD/sr_san/model.py", line 85, in encode
    seq = encoder(seq, src_mask, src_key_padding_mask)
  File "/home/zhenglc2306/.conda/envs/kdd-cup-23/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/zhenglc2306/.conda/envs/kdd-cup-23/lib/python3.10/site-packages/torch/nn/modules/transformer.py", line 306, in forward
    output = mod(output, src_mask=mask, is_causal=is_causal, src_key_padding_mask=src_key_padding_mask_for_layers)
  File "/home/zhenglc2306/.conda/envs/kdd-cup-23/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/zhenglc2306/.conda/envs/kdd-cup-23/lib/python3.10/site-packages/torch/nn/modules/transformer.py", line 573, in forward
    x = self.norm1(x + self._sa_block(x, src_mask, src_key_padding_mask))
  File "/home/zhenglc2306/.conda/envs/kdd-cup-23/lib/python3.10/site-packages/torch/nn/modules/transformer.py", line 581, in _sa_block
    x = self.self_attn(x, x, x,
  File "/home/zhenglc2306/.conda/envs/kdd-cup-23/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/zhenglc2306/.conda/envs/kdd-cup-23/lib/python3.10/site-packages/torch/nn/modules/activation.py", line 1142, in forward
    merged_mask, mask_type = self.merge_masks(attn_mask, key_padding_mask, query)
  File "/home/zhenglc2306/.conda/envs/kdd-cup-23/lib/python3.10/site-packages/torch/nn/modules/activation.py", line 1244, in merge_masks
    attn_mask_expanded = attn_mask.view(1, 1, seq_len, seq_len).expand(batch_size, self.num_heads, -1, -1)
RuntimeError: shape '[1, 1, 16, 16]' is invalid for input of size 32768

**Comment by rsamf** [comment]
First of all, I wasn't expecting anyone else to be using this, so it may not be easy to use or work right out of the box. Are you trying this code out for the KDD cup? Because if so, I need to warn you that the performance of the model doesn't exceed the baseline. Anyways, I can't tell what's happening from here. I've never seen this error. It looks like it has some problem with the src_mask or src_key_padding_mask. Unfortunately, I won't be sending much of my time maintaining this work. I wish you good luck!

**Comment by SHUzhekiNg** [comment]
ok, I'm not trying to use the code for the KDD cup actually.
And thanks again for your time and the information! Good Day!
